# -*- coding: utf-8 -*-
"""HW1_Yu_Ruiqing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zm6jRwKSsy4bpKN2z-vK1WXtYW8tlbum

## **Homework 1**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/05/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question. Please note that your programs will be tested for other sets of inputs and outputs along with the sample provided. So test your code for other inputs.

### You can submit your solutions any number of times until the deadline.

##### Q1. Write a program that prompts the user to enter a password then prints the length of the password.

```
Enter your password: hello
Your password is 5 long.
```
"""

# Type solution here
password = input("Enter your password: ")
print("Your password is", len(password), "long")

"""##### Q2. Write a program that prompts the user to enter their full name then prints the number of characters in their name (do not count spaces).

```
What is your name? Amulya Katti
Amulya Katti your name has 11 characters.
```
"""

# Type solution here
name= input("What is your name? ")
fullName = name.replace(" ", "")
print(name, "your name has", len(fullName), "characters.")

"""##### Q3. Write a program that prompts the user to enter a month (as a number), then prints the name of the month and the number of days in that month. Ensure that the user inputs a valid month and handle any error cases.

```
Enter the month number: 9
September has 30 days
```
"""

# Type solution here
months= ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
numMonth = int(input("Enter the month number: "))
while numMonth<1 or numMonth > 12:
  numMonth = int(input("Please enter a valid month number: "))
month_name= months[numMonth-1]
if month_name == "February":
	print(month_name, "has 28/29 days")
elif month_name in ("April", "June", "September", "November"):
	print(month_name, "has 30 days")
elif month_name in ("January", "March", "May", "July", "August", "October", "December"):
	print(month_name, "has 31 days")

"""##### Q4. Write a program that prompts the user to enter a loan amount, annual interest rate, and number of years  for a car loan. Then calculate and print the monthly payment amount.

Note:
```
PMT= [PV*i*((1+i)^n)]/[((1+i)^n)-1]
```
PMT is the monthly payment

PV is the loan amount

i is the interest rate per month in decimal form (interest rate percentage divided by 12)

n is the number of months (term of the loan in months)

```
Loan Amount: 30000.00
Annual Interest Rate: 4.00
Years: 5
Your monthly payment is: $552.50
```
"""

# Type solution here
PV = int(input("Loan Amount: "))
AIR = int(input("Annual Interest Rate: "))
years = int(input("Years: "))
i = AIR/100/12
month = years*12
PMT = (((1+i)**month)*PV*i)/(((1+i)**month)-1)
print("Your monthly payment is: $" + str(PMT))

"""##### Q5. Write a program to that prompts the user to enter a string. Then check whether or not the string is a palindrome.

```
Enter a string: Madam
Madam, is a palindrome!
```
"""

# Type solution here
string = input("Enter a string: ")
rev = "".join(reversed(string))
if string == rev:
  print(string, "is a palindrome!")
else:
  print(string, "is not a palindrome!")

"""##### Q6. Write a program to compute and print all possible combinations of change for \$1. Denominations to be considered – quarter, dime, nickel, penny.

Hint: Use nested loops (loops within loops for the various denominations of coins)

```
Change for $1:
0 quarters, 0 dimes, 0 nickels, 100 pennies
…
4 quarters, 0 dimes, 0 nickels, 0 pennies
```
"""

# Type solution here
print("Change for $1")
total = 100
quarters = 25
dimes = 10
nickels = 5
pennies = 1
for q in range(int(total/quarters)+1):
    for d in range(int(total/dimes)+1):
        for n in range(int(total/nickels)+1):
            for p in range(int(total/pennies)+1):
                if (q * 25 + d * 10 + n * 5 + p * 1) == total:
                    print(q, "quarters,", d, "dimes,", n, "nickels,", p, "pennies")

"""##### Q7. Ask the user to enter two positive integers between 1 and 100. Read those integers. Then output a multiplication table of the first number times the second number. 

Note: You have to ensure the entered numbers are between 1 and 100 only.

```
Please enter an integer: 5
Please enter another integer: 20
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
…
5 x 20 = 100
```
"""

# Type solution here
first = int(input("Please enter an integer: "))
while first<1 or first > 100:
  first = int(input("Please enter an integer: "))
second = int(input("Please enter another integer: "))
while second <1 or second > 100:
  second = int(input("Please enter another integer: "))
for i in range(second):
    print(first, "*", i+1, "=", first*(i+1))

"""##### Q8. Write a program to ask the user to enter a password. Then check to see if it is a valid password based on these requirements -

Must be at least 8 characters long

Must contain both uppercase and lowercase letters

Must contain at least one number between 0-9

Must contain a special character -!,@,#,$

If the password is not valid, ask the user to re-enter. This should continue until the user enters a valid password. After a valid password is entered, print Access Granted!

```
Please enter a password. Follow these requirements - 
a. Must be at least 8 characters long
b. Must contain both uppercase and lowercase letters
c. Must contain at least one number between 0-9
d. Must contain a special character -!,@,#,$
Password: HelloWorld1
Invalid password. Try again!
Password: Hello@World1
Access Granted!
```

"""

# Type solution here
password = input("Please enter a password. Follow these requirements\n"
      "a. Must be at least 8 characters long\n"
      "b. Must contain both uppercase and lowercase letters\n"
      "c. Must contain at least one number between 0-9\n"
      "d. Must contain a special character !,@,#,$\n"
      "Password: ")
valid= False
length= False
upper = False
lower = False
number = False
special = False
while not valid:
    if len(password) >= 8:
        length = True
    for i in password:
        if i.isupper():
            upper = True
        elif i.islower():
            lower = True
        elif i.isnumeric():
            number= True
        elif i == "!" or i == "@" or i == "#" or i == "$":
            special = True
    if length and upper and lower and number and special:
        valid = True
        # only all five requirements are true can the password be valid
    if not valid:
        print("Invalid password. Try again!")
        password = input("Password: ")
        # if password is no valid
print("Valid Password!")

"""##### Q9. Given the score sheet of participants in a competition, you are required to find the runner-up score. You are given scores in a list. Find the score of the runner-up.

```
list1 - [2, 3, 6, 6, 5]
runner_up - 5

list2 - [1, 7, 5, 3, 10, 4, 5, 5, 6, 11]
runner_up - 10
```
"""

# Type solution here
list1= [2, 3, 6, 6, 5]
largest=max(list1[0],list1[1]) 
secondmax=min(list1[0],list1[1]) 
n =len(list1)
for i in range(2,n): 
    if list1[i]>largest: 
        secondmax=largest
        largest=list1[i] 
    elif list1[i]>secondmax and largest != list1[i]: 
        secondmax=list1[i]
print("runner_up -", str(secondmax))